"""The crackle around a Zap-dissolving player (Modules/Weapons/damage_classes.py's own Zap),
built in code as particle systems the same way lightning.py's smite bolt is - see that file's
own docstring for the shape of this pattern.

Ported from what Source's own client code actually spawns for this (source-sdk-2013's
game/client/c_entitydissolve.cpp and game/server/EntityDissolve.cpp -
ValveSoftware/source-sdk-2013 on GitHub):

  - C_EntityDissolve::DrawModel calls AddParticle every frame the effect is active, scattered
    around the character's hitboxes - small fast "effects/spark" sparks (mostly kicked
    upward) plus soft "effects/combinemuzzle2" glow blobs (drifting any direction) - while
    the model ITSELF just tints toward flat black and eventually vanishes (see
    skeletal_shader.py's own dissolve comment: that part is the shader, not particles at
    all). Source's own two material names aren't part of this project's own asset set, so
    this reuses this project's own closest-looking stock sprites instead
    (sparkles.png/particle_glow_02.png, same swap lightning.py already makes for its own
    bendibeam/particle_glow_04).
  - For the electrical dissolve types specifically, C_EntityDissolve::DoSparks/BuildTeslaEffect
    additionally fire a genuine lightning-arc beam (TE_BEAMTESLA, "sprites/lgtning.vmt") a few
    times a second from a random point on the body outward - the actual "electricity jumping
    off them" look, distinct from (and much more visible than) the dust-like sparks/glow above.
    dissolve_arc below stands in for that beam the same way lightning.py's own smite_crackle
    stands in for Source's beam-based tesla effect there: a burst of short, bright energy
    streaks radiating from the spawn point. sprites/lgtning.vmt itself is compiled Valve game
    content (shipped in HL2/EP1/EP2's own GCF/VPK files), not part of source-sdk-2013's own
    GitHub repo (that only has engine/game CODE, never the actual textures/materials) - lgtning
    .png here is a from-scratch recreation of that sprite's own well-known look (a sharp jagged
    single strike, white-hot core, soft glow falloff, tileable along a beam's length - the same
    sprite Half-Life's tripmine/gauss gun/grapple beam have used since 1998), generated by this
    module's own asset-authoring script rather than any Valve file - see the PNG's own history
    for that script. Left greyscale/white rather than pre-tinted (unlike bendibeam.png, which
    bakes its own green tint straight into the file) specifically so Color Random below tints
    it cleanly at spawn time instead of multiplying against an already-coloured base.

Every distance/radius/speed/gravity value below is authored in SOURCE UNITS (inches), not
metres - same convention this whole particle system uses throughout (see particle_system.py's
own Effect.scale property: "Metres per Source unit... self.manager.unit_scale * self.size",
unit_scale = 0.0254). A first pass at this file authored those fields as if they were metres
directly, which silently made every dissolve particle ~39x smaller and slower than intended -
a 0.05 "radius" is 1.3mm, not 5cm - explaining why the whole effect read as faint, undersized
static instead of a body engulfed in crackling light. Every number below is deliberately
divided back out (real desired metres / 0.0254) to land at the actual intended size; blood.py's
own already-correct spark-scale numbers (radius_min=9, speed_min=15) were the calibration
check used to confirm this.

RemotePlayer calls spawn_dissolve_spark_burst once per DISSOLVE_SPARK_INTERVAL at a random
point on the dissolving body (see its own on_dissolve_spark callback) to stand in for
Source's own per-hitbox scatter without this engine having Source's own hitbox-set machinery.

  dissolve_spark  - a handful of small bright specs, mostly kicked upward, standing in for
                     Source's own "effects/spark" burst.
  dissolve_glow   - a couple of soft glowing blobs drifting outward, standing in for Source's
                     own "effects/combinemuzzle2" burst.
  dissolve_arc    - a burst of short, bright energy streaks jumping outward, standing in for
                     Source's own tesla beam (FX_BuildTesla/BuildTeslaEffect).
"""

from .pcf import Function, ParticleSystemDef

_SPARK_MATERIAL = "particle/sparkles.vmt"
_GLOW_MATERIAL = "particle/particle_glow_02.vmt"
_ARC_MATERIAL = "particle/lgtning.vmt"


def _fn(name, **params):
    return Function(name, params)


def _spark():
    return ParticleSystemDef(
        "dissolve_spark",
        # 250, not 60 - RemotePlayer now fires DISSOLVE_SPARK_BURST_COUNT (4) of these every
        # DISSOLVE_SPARK_INTERVAL, so the steady-state live count is a good deal higher than
        # a single-point burst would need; too low a cap here would just cull the newest
        # particles early and undo the density increase.
        {"max_particles": 250, "material": _SPARK_MATERIAL, "radius": 0.05, "color": (255, 255, 255, 255)},
        emitters=[_fn("emit_instantaneously", num_to_emit=3)],
        initializers=[
            _fn("Position Within Sphere Random", distance_min=0.0, distance_max=2.0,
                speed_min=0.0, speed_max=0.0),
            # Mostly kicked upward with a little scatter (local Z = up - see
            # particle_system.py's own SOURCE_TO_WORLD/frame docstring), same as Source's own
            # sParticle->m_vecVelocity for a non-CORE dissolve spark - real 0.4-1.6 m/s
            # (÷0.0254, see this module's own docstring on the Source-units convention).
            _fn("Velocity Random", speed_in_local_coordinate_system_min=(-4.0, -4.0, 16.0),
                speed_in_local_coordinate_system_max=(4.0, 4.0, 63.0)),
            _fn("Lifetime Random", lifetime_min=0.4, lifetime_max=0.5),
            _fn("Radius Random", radius_min=1.5, radius_max=3.0),
            _fn("Color Random", color1=(220, 235, 255, 255), color2=(255, 255, 255, 255)),
            _fn("Alpha Random", alpha_min=230, alpha_max=255),
        ],
        operators=[
            _fn("Movement Basic", gravity=(0.0, 0.0, -250.0), drag=0.1),
            _fn("Alpha Fade Out Random", **{"fade out time min": 0.15, "fade out time max": 0.25,
                                            "proportional 0/1": True}),
        ],
        renderers=[_fn("render_animated_sprites")],
    )


def _glow():
    return ParticleSystemDef(
        "dissolve_glow",
        # 48, not 32 - same DISSOLVE_SPARK_BURST_COUNT reasoning as dissolve_spark above.
        {"max_particles": 48, "material": _GLOW_MATERIAL, "radius": 0.1, "color": (255, 255, 255, 255)},
        emitters=[_fn("emit_instantaneously", num_to_emit=2)],
        initializers=[
            _fn("Position Within Sphere Random", distance_min=0.0, distance_max=2.0,
                speed_min=0.0, speed_max=0.0),
            # Real -1.6 to 3.2 m/s (÷0.0254 - see this module's own docstring).
            _fn("Velocity Random", speed_in_local_coordinate_system_min=(-4.0, -4.0, -63.0),
                speed_in_local_coordinate_system_max=(4.0, 4.0, 126.0)),
            _fn("Lifetime Random", lifetime_min=0.1, lifetime_max=0.1),
            # Real ~0.3-0.6m - big enough that several overlapping blobs at once actually
            # engulf the body in light instead of leaving isolated pinpricks (see this
            # module's own docstring on the unit-scale bug this replaces).
            _fn("Radius Random", radius_min=12.0, radius_max=24.0),
            _fn("Color Random", color1=(200, 225, 255, 255), color2=(255, 255, 255, 255)),
            _fn("Alpha Random", alpha_min=220, alpha_max=255),
        ],
        operators=[
            _fn("Alpha Fade Out Random", **{"fade out time min": 0.05, "fade out time max": 0.1,
                                            "proportional 0/1": True}),
        ],
        renderers=[_fn("render_animated_sprites")],
    )


def _arc():
    return ParticleSystemDef(
        "dissolve_arc",
        {"max_particles": 60, "material": _ARC_MATERIAL, "radius": 1.0, "color": (255, 255, 255, 255)},
        emitters=[_fn("emit_instantaneously", num_to_emit=3)],
        initializers=[
            # A short burst jumping outward in any direction from the spawn point (unlike
            # smite_bolt/crackle's mostly-upward bias - this is meant to read as electricity
            # arcing off the body's SURFACE, not a strike from above), radius kept small
            # (real ~0.15m, ÷0.0254 - see this module's own docstring) since it's meant to
            # hug the body rather than fill the room.
            _fn("Position Within Sphere Random", distance_min=0.0, distance_max=6.0,
                speed_min=250.0, speed_max=500.0, speed_random_exponent=0.7),
            _fn("Lifetime Random", lifetime_min=0.06, lifetime_max=0.12),
            _fn("Radius Random", radius_min=1.5, radius_max=3.0),
            _fn("Sequence Random", sequence_min=0, sequence_max=0),
            _fn("Trail Length Random", length_min=0.05, length_max=0.12),
            _fn("Color Random", color1=(150, 200, 255, 255), color2=(255, 255, 255, 255)),
            _fn("Alpha Random", alpha_min=220, alpha_max=255),
        ],
        operators=[
            _fn("Alpha Fade Out Random", **{"fade out time min": 0.04, "fade out time max": 0.08,
                                            "proportional 0/1": True}),
        ],
        # min/max length are ALSO scaled by self.scale (particle_system.py's own _pack, unlike
        # trail_time itself which is a plain duration) - real ~0.15-0.8m, ÷0.0254.
        renderers=[_fn("render_sprite_trail", **{"min length": 6.0, "max length": 32.0,
                                                 "length fade in time": 0.0, "animation rate": 0.0})],
    )


def register_dissolve_sparks(manager):
    """Adds dissolve_spark/dissolve_glow/dissolve_arc to a ParticleManager - see app.py's own
    spawn_dissolve_spark_burst/spawn_dissolve_arc for where they're actually spawned
    (RemotePlayer's own on_dissolve_spark/on_dissolve_arc callbacks, wired up there)."""
    for definition in (_spark(), _glow(), _arc()):
        manager.definitions[definition.name] = definition
